### ISSUE TITLE
route limit affected by global requests?

### ISSUE THREAD

**Issue by dmidnight** [futurestudio/hapi-rate-limitor#110]
I have a rate limit on a route /test of 20/min

I have a global rate limit of 300/min

When I request GET /test once, and then request 5 other routes, then call /test again, I can see that the rate limit headers reflect 7 total requests against /test instead of the correct number (2)

Am I using this wrong or is this a bug?

**Comment by dmidnight** [comment]
Node: v12
Hapi: 18.4.1
hapi-rate-limitor: 2.12.0

**Comment by marcuspoehls** [comment]
@dmidnight Hey, thank you for reporting this behavior. I was thinking about it for the last day and it's currently the correct behavior. The code is currently structured the way that the global rate limit affects routes with a custom rate limit.

Please give me some days to think about this problem. I ran into the same issues a while ago. We should make sure it gets changed.

Your expected behavior is that routes with a custom rate limit (in your case the `/test` route) are not affected by the global (server wide default) rate limit. Correct?

**Comment by dmidnight** [comment]
Yes, I would expect to be able to hit /test 20 times a minute regardless of other rate limits on other routes.

Thanks for looking into this, and providing an otherwise great tool!

**Comment by marcuspoehls** [comment]
@dmidnight I’ve created a PR implementing the desired handling. The PR introduces a split between route-level max attempts and the default server-wide max attempts.

In case a route has it’s own `max` configuration, it will not be affected by any global rate limiting state and previous requests to other pages.

You may have a look at #111.

I’ll let this sit at least until Monday. This gives us some time to think about the implementation. I appreciate any feedback :)

**Comment by dmidnight** [comment]
LGTM!

**Comment by marcuspoehls** [comment]
Sweet! I'll publish a new release in the `2.x` and `3.x` release line over the weekend.

**Comment by marcuspoehls** [comment]
@dmidnight I’ve released `2.13.0` and `3.1.0` with the refined route-level max attempts handling. Thank you for reporting this issue leading to an improved rate-limit handling 😃
